package handlers

import (
	"fmt"
	"log"
	"net/http"
	"strings"

	"github.com/e2b-dev/infra/packages/docker-reverse-proxy/internal/cache"
	"github.com/e2b-dev/infra/packages/docker-reverse-proxy/internal/constants"
	"github.com/e2b-dev/infra/packages/docker-reverse-proxy/internal/utils"
	"github.com/e2b-dev/infra/packages/shared/pkg/consts"
)

func (a *APIStore) Proxy(w http.ResponseWriter, req *http.Request) {
	// Check if the request is for the correct repository
	path := req.URL.String()
	log.Printf("[DEBUG] Proxy - Handling request: %s %s", req.Method, path)

	// Validate the token by checking if the generated token is in the cache
	authHeader := req.Header.Get("Authorization")
	e2bToken := strings.TrimPrefix(authHeader, "Bearer ")
	token, err := a.AuthCache.Get(e2bToken)
	if err != nil {
		log.Printf("Error while getting token for %s: %s\n", path, err)
		utils.SetDockerUnauthorizedHeaders(w)
		return
	}

	log.Printf("[DEBUG] Proxy - Found token in cache for template ID: %s", token.TemplateID)

	// Handle based on cloud provider
	if constants.CurrentCloudProvider == constants.GCP {
		// Set the Authorization header for the request to the real docker registry
		req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", token.DockerToken))
		log.Printf("[DEBUG] Proxy - Set Bearer Authorization header for GCP")
		handleGCPProxy(a, w, req, path, token)
	} else if constants.CurrentCloudProvider == constants.AWS {
		// For AWS ECR, we'll handle authentication in handleAWSProxy
		log.Printf("[DEBUG] Proxy - Delegating to AWS ECR proxy handler")
		handleAWSProxy(a, w, req, path, token)
	} else {
		log.Printf("Unsupported cloud provider for path: %s\n", path)
		w.WriteHeader(http.StatusInternalServerError)
	}
}

func handleGCPProxy(a *APIStore, w http.ResponseWriter, req *http.Request, path string, token *cache.AccessTokenData) {
	// Allow access to the GCP artifact uploads.
	// The url is generated by repository and sent as a Location header from the /blobs/upload request
	// https://distribution.github.io/distribution/spec/api/#starting-an-upload
	// Other methods than PATCH require the Authorization header
	if strings.HasPrefix(path, constants.GCPArtifactUploadPrefix) {
		a.ServeHTTP(w, req)
		return
	}

	repoPrefix := "/v2/e2b/custom-envs/"
	realRepoPrefix := fmt.Sprintf("/v2/%s/%s/", consts.GCPProject, consts.DockerRegistry)
	if !strings.HasPrefix(path, repoPrefix) && !strings.HasPrefix(path, realRepoPrefix) {
		// The request shouldn't need any other endpoints, we deny access
		log.Printf("No matching route found for path: %s\n", path)

		w.WriteHeader(http.StatusForbidden)
		return
	}

	templateID := token.TemplateID

	// Uploading blobs doesn't have the template ID in the path
	if strings.HasPrefix(path, fmt.Sprintf("%spkg/blobs/uploads/", realRepoPrefix)) {
		a.ServeHTTP(w, req)

		return
	}

	pathInRepo := strings.TrimPrefix(path, repoPrefix)
	templateWithBuildID := strings.Split(strings.Split(pathInRepo, "/")[0], ":")

	// If the template ID in the path is different from the token template ID, deny access
	if templateWithBuildID[0] != templateID {
		w.WriteHeader(http.StatusForbidden)
		log.Printf("Access denied for template: %s\n", templateID)

		return
	}

	// Set the host and access token for the real docker registry
	req.URL.Path = strings.Replace(req.URL.Path, repoPrefix, realRepoPrefix, 1)

	a.ServeHTTP(w, req)
}

func handleAWSProxy(a *APIStore, w http.ResponseWriter, req *http.Request, path string, token *cache.AccessTokenData) {
	templateID := token.TemplateID

	log.Printf("[INFO] AWS Proxy - Request: %s %s", req.Method, req.URL.Path)

	// Use cached token instead of fetching a new one each time
	req.Header.Set("Authorization", fmt.Sprintf("Basic %s", token.DockerToken))
	log.Printf("[DEBUG] AWS Proxy - Set Basic auth header for AWS ECR using cached token")

	// Client request path prefix
	repoPrefix := "/v2/e2b/custom-envs/"

	// For AWS ECR, use base_repo_name as the base repository name
	baseRepo := strings.Trim(constants.AWSECRRepository, "/")

	// Set the real repository prefix, including templateID
	realRepoPrefix := fmt.Sprintf("/v2/%s/%s/", baseRepo, templateID)

	// If path does not start with client repo prefix, deny access
	if !strings.HasPrefix(path, repoPrefix) {
		log.Printf("[ERROR] No matching route found for path: %s", path)
		w.WriteHeader(http.StatusForbidden)
		return
	}

	// Extract template ID from path
	pathInRepo := strings.TrimPrefix(path, repoPrefix)
	templateWithBuildID := strings.Split(strings.Split(pathInRepo, "/")[0], ":")

	// If template ID in path differs from token's, deny access
	if templateWithBuildID[0] != templateID {
		log.Printf("[ERROR] Access denied: path template ID %s doesn't match token template ID %s",
			templateWithBuildID[0], templateID)
		w.WriteHeader(http.StatusForbidden)
		return
	}

	// Replace path prefix, ensuring templateID is not duplicated
	newPath := strings.Replace(req.URL.Path,
		fmt.Sprintf("%s%s", repoPrefix, templateID),
		realRepoPrefix,
		1)

	// Remove any double slashes
	newPath = strings.ReplaceAll(newPath, "//", "/")
	req.URL.Path = newPath

	log.Printf("[DEBUG] AWS Proxy - Converted path: %s", req.URL.Path)

	// Proxy the request
	a.ServeHTTP(w, req)
}
