// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: template-manager.proto

package template_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateBuildState int32

const (
	TemplateBuildState_Building  TemplateBuildState = 0
	TemplateBuildState_Failed    TemplateBuildState = 1
	TemplateBuildState_Completed TemplateBuildState = 2
)

// Enum value maps for TemplateBuildState.
var (
	TemplateBuildState_name = map[int32]string{
		0: "Building",
		1: "Failed",
		2: "Completed",
	}
	TemplateBuildState_value = map[string]int32{
		"Building":  0,
		"Failed":    1,
		"Completed": 2,
	}
)

func (x TemplateBuildState) Enum() *TemplateBuildState {
	p := new(TemplateBuildState)
	*p = x
	return p
}

func (x TemplateBuildState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateBuildState) Descriptor() protoreflect.EnumDescriptor {
	return file_template_manager_proto_enumTypes[0].Descriptor()
}

func (TemplateBuildState) Type() protoreflect.EnumType {
	return &file_template_manager_proto_enumTypes[0]
}

func (x TemplateBuildState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateBuildState.Descriptor instead.
func (TemplateBuildState) EnumDescriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{0}
}

type LogLevel int32

const (
	LogLevel_Debug LogLevel = 0
	LogLevel_Info  LogLevel = 1
	LogLevel_Warn  LogLevel = 2
	LogLevel_Error LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "Debug",
		1: "Info",
		2: "Warn",
		3: "Error",
	}
	LogLevel_value = map[string]int32{
		"Debug": 0,
		"Info":  1,
		"Warn":  2,
		"Error": 3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_template_manager_proto_enumTypes[1].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_template_manager_proto_enumTypes[1]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{1}
}

type HealthState int32

const (
	HealthState_Healthy  HealthState = 0
	HealthState_Draining HealthState = 1
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "Healthy",
		1: "Draining",
	}
	HealthState_value = map[string]int32{
		"Healthy":  0,
		"Draining": 1,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_template_manager_proto_enumTypes[2].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_template_manager_proto_enumTypes[2]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{2}
}

type TemplateStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	FilesHash     *string                `protobuf:"bytes,3,opt,name=filesHash,proto3,oneof" json:"filesHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateStep) Reset() {
	*x = TemplateStep{}
	mi := &file_template_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateStep) ProtoMessage() {}

func (x *TemplateStep) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateStep.ProtoReflect.Descriptor instead.
func (*TemplateStep) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemplateStep) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TemplateStep) GetFilesHash() string {
	if x != nil && x.FilesHash != nil {
		return *x.FilesHash
	}
	return ""
}

type TemplateConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TemplateID         string                 `protobuf:"bytes,1,opt,name=templateID,proto3" json:"templateID,omitempty"`
	BuildID            string                 `protobuf:"bytes,2,opt,name=buildID,proto3" json:"buildID,omitempty"`
	MemoryMB           int32                  `protobuf:"varint,3,opt,name=memoryMB,proto3" json:"memoryMB,omitempty"`
	VCpuCount          int32                  `protobuf:"varint,4,opt,name=vCpuCount,proto3" json:"vCpuCount,omitempty"`
	DiskSizeMB         int32                  `protobuf:"varint,5,opt,name=diskSizeMB,proto3" json:"diskSizeMB,omitempty"`
	KernelVersion      string                 `protobuf:"bytes,6,opt,name=kernelVersion,proto3" json:"kernelVersion,omitempty"`
	FirecrackerVersion string                 `protobuf:"bytes,7,opt,name=firecrackerVersion,proto3" json:"firecrackerVersion,omitempty"`
	StartCommand       string                 `protobuf:"bytes,8,opt,name=startCommand,proto3" json:"startCommand,omitempty"`
	HugePages          bool                   `protobuf:"varint,9,opt,name=hugePages,proto3" json:"hugePages,omitempty"`
	ReadyCommand       string                 `protobuf:"bytes,10,opt,name=readyCommand,proto3" json:"readyCommand,omitempty"`
	FromImage          string                 `protobuf:"bytes,11,opt,name=fromImage,proto3" json:"fromImage,omitempty"`
	Steps              []*TemplateStep        `protobuf:"bytes,12,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TemplateConfig) Reset() {
	*x = TemplateConfig{}
	mi := &file_template_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateConfig) ProtoMessage() {}

func (x *TemplateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateConfig.ProtoReflect.Descriptor instead.
func (*TemplateConfig) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateConfig) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *TemplateConfig) GetBuildID() string {
	if x != nil {
		return x.BuildID
	}
	return ""
}

func (x *TemplateConfig) GetMemoryMB() int32 {
	if x != nil {
		return x.MemoryMB
	}
	return 0
}

func (x *TemplateConfig) GetVCpuCount() int32 {
	if x != nil {
		return x.VCpuCount
	}
	return 0
}

func (x *TemplateConfig) GetDiskSizeMB() int32 {
	if x != nil {
		return x.DiskSizeMB
	}
	return 0
}

func (x *TemplateConfig) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *TemplateConfig) GetFirecrackerVersion() string {
	if x != nil {
		return x.FirecrackerVersion
	}
	return ""
}

func (x *TemplateConfig) GetStartCommand() string {
	if x != nil {
		return x.StartCommand
	}
	return ""
}

func (x *TemplateConfig) GetHugePages() bool {
	if x != nil {
		return x.HugePages
	}
	return false
}

func (x *TemplateConfig) GetReadyCommand() string {
	if x != nil {
		return x.ReadyCommand
	}
	return ""
}

func (x *TemplateConfig) GetFromImage() string {
	if x != nil {
		return x.FromImage
	}
	return ""
}

func (x *TemplateConfig) GetSteps() []*TemplateStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type TemplateCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *TemplateConfig        `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateCreateRequest) Reset() {
	*x = TemplateCreateRequest{}
	mi := &file_template_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateCreateRequest) ProtoMessage() {}

func (x *TemplateCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateCreateRequest.ProtoReflect.Descriptor instead.
func (*TemplateCreateRequest) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateCreateRequest) GetTemplate() *TemplateConfig {
	if x != nil {
		return x.Template
	}
	return nil
}

type TemplateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateID    string                 `protobuf:"bytes,1,opt,name=templateID,proto3" json:"templateID,omitempty"`
	BuildID       string                 `protobuf:"bytes,2,opt,name=buildID,proto3" json:"buildID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateStatusRequest) Reset() {
	*x = TemplateStatusRequest{}
	mi := &file_template_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateStatusRequest) ProtoMessage() {}

func (x *TemplateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateStatusRequest.ProtoReflect.Descriptor instead.
func (*TemplateStatusRequest) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{3}
}

func (x *TemplateStatusRequest) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *TemplateStatusRequest) GetBuildID() string {
	if x != nil {
		return x.BuildID
	}
	return ""
}

// Data required for deleting a template.
type TemplateBuildDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildID       string                 `protobuf:"bytes,1,opt,name=buildID,proto3" json:"buildID,omitempty"`
	TemplateID    string                 `protobuf:"bytes,2,opt,name=templateID,proto3" json:"templateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateBuildDeleteRequest) Reset() {
	*x = TemplateBuildDeleteRequest{}
	mi := &file_template_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBuildDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBuildDeleteRequest) ProtoMessage() {}

func (x *TemplateBuildDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBuildDeleteRequest.ProtoReflect.Descriptor instead.
func (*TemplateBuildDeleteRequest) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{4}
}

func (x *TemplateBuildDeleteRequest) GetBuildID() string {
	if x != nil {
		return x.BuildID
	}
	return ""
}

func (x *TemplateBuildDeleteRequest) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

type TemplateBuildMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RootfsSizeKey  int32                  `protobuf:"varint,1,opt,name=rootfsSizeKey,proto3" json:"rootfsSizeKey,omitempty"`
	EnvdVersionKey string                 `protobuf:"bytes,2,opt,name=envdVersionKey,proto3" json:"envdVersionKey,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TemplateBuildMetadata) Reset() {
	*x = TemplateBuildMetadata{}
	mi := &file_template_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBuildMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBuildMetadata) ProtoMessage() {}

func (x *TemplateBuildMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBuildMetadata.ProtoReflect.Descriptor instead.
func (*TemplateBuildMetadata) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{5}
}

func (x *TemplateBuildMetadata) GetRootfsSizeKey() int32 {
	if x != nil {
		return x.RootfsSizeKey
	}
	return 0
}

func (x *TemplateBuildMetadata) GetEnvdVersionKey() string {
	if x != nil {
		return x.EnvdVersionKey
	}
	return ""
}

type TemplateBuildLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Level         LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=LogLevel" json:"level,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateBuildLogEntry) Reset() {
	*x = TemplateBuildLogEntry{}
	mi := &file_template_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBuildLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBuildLogEntry) ProtoMessage() {}

func (x *TemplateBuildLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBuildLogEntry.ProtoReflect.Descriptor instead.
func (*TemplateBuildLogEntry) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{6}
}

func (x *TemplateBuildLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TemplateBuildLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TemplateBuildLogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_Debug
}

func (x *TemplateBuildLogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type TemplateBuildStatusReason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Step          *string                `protobuf:"bytes,2,opt,name=step,proto3,oneof" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateBuildStatusReason) Reset() {
	*x = TemplateBuildStatusReason{}
	mi := &file_template_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBuildStatusReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBuildStatusReason) ProtoMessage() {}

func (x *TemplateBuildStatusReason) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBuildStatusReason.ProtoReflect.Descriptor instead.
func (*TemplateBuildStatusReason) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{7}
}

func (x *TemplateBuildStatusReason) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TemplateBuildStatusReason) GetStep() string {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return ""
}

// Logs from template build
type TemplateBuildStatusResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        TemplateBuildState         `protobuf:"varint,1,opt,name=status,proto3,enum=TemplateBuildState" json:"status,omitempty"`
	Metadata      *TemplateBuildMetadata     `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	LogEntries    []*TemplateBuildLogEntry   `protobuf:"bytes,3,rep,name=logEntries,proto3" json:"logEntries,omitempty"`
	Reason        *TemplateBuildStatusReason `protobuf:"bytes,4,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateBuildStatusResponse) Reset() {
	*x = TemplateBuildStatusResponse{}
	mi := &file_template_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBuildStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBuildStatusResponse) ProtoMessage() {}

func (x *TemplateBuildStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBuildStatusResponse.ProtoReflect.Descriptor instead.
func (*TemplateBuildStatusResponse) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{8}
}

func (x *TemplateBuildStatusResponse) GetStatus() TemplateBuildState {
	if x != nil {
		return x.Status
	}
	return TemplateBuildState_Building
}

func (x *TemplateBuildStatusResponse) GetMetadata() *TemplateBuildMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TemplateBuildStatusResponse) GetLogEntries() []*TemplateBuildLogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

func (x *TemplateBuildStatusResponse) GetReason() *TemplateBuildStatusReason {
	if x != nil {
		return x.Reason
	}
	return nil
}

type HealthStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthState            `protobuf:"varint,1,opt,name=status,proto3,enum=HealthState" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatusResponse) Reset() {
	*x = HealthStatusResponse{}
	mi := &file_template_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatusResponse) ProtoMessage() {}

func (x *HealthStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatusResponse.ProtoReflect.Descriptor instead.
func (*HealthStatusResponse) Descriptor() ([]byte, []int) {
	return file_template_manager_proto_rawDescGZIP(), []int{9}
}

func (x *HealthStatusResponse) GetStatus() HealthState {
	if x != nil {
		return x.Status
	}
	return HealthState_Healthy
}

var File_template_manager_proto protoreflect.FileDescriptor

const file_template_manager_proto_rawDesc = "" +
	"\n" +
	"\x16template-manager.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\fTemplateStep\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12!\n" +
	"\tfilesHash\x18\x03 \x01(\tH\x00R\tfilesHash\x88\x01\x01B\f\n" +
	"\n" +
	"_filesHash\"\xa3\x03\n" +
	"\x0eTemplateConfig\x12\x1e\n" +
	"\n" +
	"templateID\x18\x01 \x01(\tR\n" +
	"templateID\x12\x18\n" +
	"\abuildID\x18\x02 \x01(\tR\abuildID\x12\x1a\n" +
	"\bmemoryMB\x18\x03 \x01(\x05R\bmemoryMB\x12\x1c\n" +
	"\tvCpuCount\x18\x04 \x01(\x05R\tvCpuCount\x12\x1e\n" +
	"\n" +
	"diskSizeMB\x18\x05 \x01(\x05R\n" +
	"diskSizeMB\x12$\n" +
	"\rkernelVersion\x18\x06 \x01(\tR\rkernelVersion\x12.\n" +
	"\x12firecrackerVersion\x18\a \x01(\tR\x12firecrackerVersion\x12\"\n" +
	"\fstartCommand\x18\b \x01(\tR\fstartCommand\x12\x1c\n" +
	"\thugePages\x18\t \x01(\bR\thugePages\x12\"\n" +
	"\freadyCommand\x18\n" +
	" \x01(\tR\freadyCommand\x12\x1c\n" +
	"\tfromImage\x18\v \x01(\tR\tfromImage\x12#\n" +
	"\x05steps\x18\f \x03(\v2\r.TemplateStepR\x05steps\"D\n" +
	"\x15TemplateCreateRequest\x12+\n" +
	"\btemplate\x18\x01 \x01(\v2\x0f.TemplateConfigR\btemplate\"Q\n" +
	"\x15TemplateStatusRequest\x12\x1e\n" +
	"\n" +
	"templateID\x18\x01 \x01(\tR\n" +
	"templateID\x12\x18\n" +
	"\abuildID\x18\x02 \x01(\tR\abuildID\"V\n" +
	"\x1aTemplateBuildDeleteRequest\x12\x18\n" +
	"\abuildID\x18\x01 \x01(\tR\abuildID\x12\x1e\n" +
	"\n" +
	"templateID\x18\x02 \x01(\tR\n" +
	"templateID\"e\n" +
	"\x15TemplateBuildMetadata\x12$\n" +
	"\rrootfsSizeKey\x18\x01 \x01(\x05R\rrootfsSizeKey\x12&\n" +
	"\x0eenvdVersionKey\x18\x02 \x01(\tR\x0eenvdVersionKey\"\x83\x02\n" +
	"\x15TemplateBuildLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x05level\x18\x03 \x01(\x0e2\t.LogLevelR\x05level\x12:\n" +
	"\x06fields\x18\x04 \x03(\v2\".TemplateBuildLogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x19TemplateBuildStatusReason\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\x04step\x18\x02 \x01(\tH\x00R\x04step\x88\x01\x01B\a\n" +
	"\x05_step\"\xfa\x01\n" +
	"\x1bTemplateBuildStatusResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.TemplateBuildStateR\x06status\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.TemplateBuildMetadataR\bmetadata\x126\n" +
	"\n" +
	"logEntries\x18\x03 \x03(\v2\x16.TemplateBuildLogEntryR\n" +
	"logEntries\x127\n" +
	"\x06reason\x18\x04 \x01(\v2\x1a.TemplateBuildStatusReasonH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"<\n" +
	"\x14HealthStatusResponse\x12$\n" +
	"\x06status\x18\x01 \x01(\x0e2\f.HealthStateR\x06status*=\n" +
	"\x12TemplateBuildState\x12\f\n" +
	"\bBuilding\x10\x00\x12\n" +
	"\n" +
	"\x06Failed\x10\x01\x12\r\n" +
	"\tCompleted\x10\x02*4\n" +
	"\bLogLevel\x12\t\n" +
	"\x05Debug\x10\x00\x12\b\n" +
	"\x04Info\x10\x01\x12\b\n" +
	"\x04Warn\x10\x02\x12\t\n" +
	"\x05Error\x10\x03*(\n" +
	"\vHealthState\x12\v\n" +
	"\aHealthy\x10\x00\x12\f\n" +
	"\bDraining\x10\x012\xab\x02\n" +
	"\x0fTemplateService\x12@\n" +
	"\x0eTemplateCreate\x12\x16.TemplateCreateRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x13TemplateBuildStatus\x12\x16.TemplateStatusRequest\x1a\x1c.TemplateBuildStatusResponse\x12J\n" +
	"\x13TemplateBuildDelete\x12\x1b.TemplateBuildDeleteRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\fHealthStatus\x12\x16.google.protobuf.Empty\x1a\x15.HealthStatusResponseB3Z1https://github.com/e2b-dev/infra/template-managerb\x06proto3"

var (
	file_template_manager_proto_rawDescOnce sync.Once
	file_template_manager_proto_rawDescData []byte
)

func file_template_manager_proto_rawDescGZIP() []byte {
	file_template_manager_proto_rawDescOnce.Do(func() {
		file_template_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_template_manager_proto_rawDesc), len(file_template_manager_proto_rawDesc)))
	})
	return file_template_manager_proto_rawDescData
}

var file_template_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_template_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_template_manager_proto_goTypes = []any{
	(TemplateBuildState)(0),             // 0: TemplateBuildState
	(LogLevel)(0),                       // 1: LogLevel
	(HealthState)(0),                    // 2: HealthState
	(*TemplateStep)(nil),                // 3: TemplateStep
	(*TemplateConfig)(nil),              // 4: TemplateConfig
	(*TemplateCreateRequest)(nil),       // 5: TemplateCreateRequest
	(*TemplateStatusRequest)(nil),       // 6: TemplateStatusRequest
	(*TemplateBuildDeleteRequest)(nil),  // 7: TemplateBuildDeleteRequest
	(*TemplateBuildMetadata)(nil),       // 8: TemplateBuildMetadata
	(*TemplateBuildLogEntry)(nil),       // 9: TemplateBuildLogEntry
	(*TemplateBuildStatusReason)(nil),   // 10: TemplateBuildStatusReason
	(*TemplateBuildStatusResponse)(nil), // 11: TemplateBuildStatusResponse
	(*HealthStatusResponse)(nil),        // 12: HealthStatusResponse
	nil,                                 // 13: TemplateBuildLogEntry.FieldsEntry
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 15: google.protobuf.Empty
}
var file_template_manager_proto_depIdxs = []int32{
	3,  // 0: TemplateConfig.steps:type_name -> TemplateStep
	4,  // 1: TemplateCreateRequest.template:type_name -> TemplateConfig
	14, // 2: TemplateBuildLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 3: TemplateBuildLogEntry.level:type_name -> LogLevel
	13, // 4: TemplateBuildLogEntry.fields:type_name -> TemplateBuildLogEntry.FieldsEntry
	0,  // 5: TemplateBuildStatusResponse.status:type_name -> TemplateBuildState
	8,  // 6: TemplateBuildStatusResponse.metadata:type_name -> TemplateBuildMetadata
	9,  // 7: TemplateBuildStatusResponse.logEntries:type_name -> TemplateBuildLogEntry
	10, // 8: TemplateBuildStatusResponse.reason:type_name -> TemplateBuildStatusReason
	2,  // 9: HealthStatusResponse.status:type_name -> HealthState
	5,  // 10: TemplateService.TemplateCreate:input_type -> TemplateCreateRequest
	6,  // 11: TemplateService.TemplateBuildStatus:input_type -> TemplateStatusRequest
	7,  // 12: TemplateService.TemplateBuildDelete:input_type -> TemplateBuildDeleteRequest
	15, // 13: TemplateService.HealthStatus:input_type -> google.protobuf.Empty
	15, // 14: TemplateService.TemplateCreate:output_type -> google.protobuf.Empty
	11, // 15: TemplateService.TemplateBuildStatus:output_type -> TemplateBuildStatusResponse
	15, // 16: TemplateService.TemplateBuildDelete:output_type -> google.protobuf.Empty
	12, // 17: TemplateService.HealthStatus:output_type -> HealthStatusResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_template_manager_proto_init() }
func file_template_manager_proto_init() {
	if File_template_manager_proto != nil {
		return
	}
	file_template_manager_proto_msgTypes[0].OneofWrappers = []any{}
	file_template_manager_proto_msgTypes[7].OneofWrappers = []any{}
	file_template_manager_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_template_manager_proto_rawDesc), len(file_template_manager_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_template_manager_proto_goTypes,
		DependencyIndexes: file_template_manager_proto_depIdxs,
		EnumInfos:         file_template_manager_proto_enumTypes,
		MessageInfos:      file_template_manager_proto_msgTypes,
	}.Build()
	File_template_manager_proto = out.File
	file_template_manager_proto_goTypes = nil
	file_template_manager_proto_depIdxs = nil
}
