#!/bin/bash
set -e

export LC_ALL=C

generate_uuid() {
    if command -v uuidgen &> /dev/null; then
        uuidgen | tr '[:upper:]' '[:lower:]'
    else
        cat /proc/sys/kernel/random/uuid
    fi
}

generate_hex_key() {
    openssl rand -hex 20
}

# SHA-256 hash matching Go's base64.RawStdEncoding (standard alphabet, no padding)
# Input: 40-char hex string (20 bytes)
# Output: $sha256$<base64_standard_no_padding>
sha256_hash() {
    local hex_value="$1"
    local hash_base64
    hash_base64=$(echo -n "$hex_value" | xxd -r -p | openssl dgst -sha256 -binary | openssl base64 -A | sed 's/=*$//')
    echo "\$sha256\$$hash_base64"
}

# Generate credentials
TEAM_ID=$(generate_uuid)

AT_HEX=$(generate_hex_key)
ACCESS_TOKEN="sk_e2b_${AT_HEX}"
ACCESS_TOKEN_HASH=$(sha256_hash "$AT_HEX")
AT_MASK_PREFIX="${AT_HEX:0:2}"
AT_MASK_SUFFIX="${AT_HEX: -4}"

AK_HEX=$(generate_hex_key)
TEAM_API_KEY="e2b_${AK_HEX}"
API_KEY_HASH=$(sha256_hash "$AK_HEX")
AK_MASK_PREFIX="${AK_HEX:0:2}"
AK_MASK_SUFFIX="${AK_HEX: -4}"

# Write config.json (plaintext tokens for client use)
cat << EOF > config.json
{
    "email": "e2b@example.com",
    "teamId": "$TEAM_ID",
    "accessToken": "$ACCESS_TOKEN",
    "teamApiKey": "$TEAM_API_KEY",
    "cloud": "aws",
    "region": "us-east-1"
}
EOF

# Remove old E2B config block from config.properties before appending
sed -i '/^# E2B/,/^akMaskSuffix=/d' /opt/config.properties 2>/dev/null || true
sed -i '/^teamId=/d; /^accessToken=/d; /^teamApiKey=/d; /^accessTokenHash=/d; /^apiKeyHash=/d; /^atMask/d; /^akMask/d' /opt/config.properties 2>/dev/null || true

cat << EOF >> /opt/config.properties

# E2B credentials (generated by init-config.sh)
teamId=$TEAM_ID
accessToken=$ACCESS_TOKEN
teamApiKey=$TEAM_API_KEY
accessTokenHash=$ACCESS_TOKEN_HASH
apiKeyHash=$API_KEY_HASH
atMaskPrefix=$AT_MASK_PREFIX
atMaskSuffix=$AT_MASK_SUFFIX
akMaskPrefix=$AK_MASK_PREFIX
akMaskSuffix=$AK_MASK_SUFFIX
EOF

echo "Generated credentials:"
echo "  Team ID:      $TEAM_ID"
echo "  Access Token: $ACCESS_TOKEN"
echo "  API Key:      $TEAM_API_KEY"
