version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: migration-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - .:/sql
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
